На данном семинаре мы изучим библиотеку [numpy](https://numpy.org/). numpy - очень удобная и быстрая библиотека, которая предсоставляет возможность выполнять различные операции над массивами и матрицами. В машинном обучении многие операции работы с данными могут быть представлены, как операции из линейной алгебры. Именно поэтому знание этой библиотеки очень важно.

Для начала познакомимся с базовым объектом в numpy - numpy.ndarray

In [0]:
import numpy as np

In [0]:
array = np.array([1, 2, 4])

Код выше создал вектор длины 3. Теперь мы можем выполнять различные арифметические операции над этим вектором.

In [0]:
array

array([1, 2, 4])

In [0]:
array * 2

array([2, 4, 8])

In [0]:
array + 5

array([6, 7, 9])

Мы можем выполнять поэлементные операции на массивах одинаковой длины.

In [0]:
array_2 = np.array([9, 2, 0])

In [0]:
array + array_2

array([10,  4,  4])

In [0]:
array * array_2

array([9, 4, 0])

С массивами можно работать как с листами и вытаскивать оттуда элементы по индексу. В тоже время, можно использовать индексацию по условию и вытаскивать элементы с помощью булевой маски.

In [0]:
array[1]

2

In [0]:
array[1:]

array([2, 4])

In [0]:
print(array_2 > 0)
print(array[array_2 > 0])

[ True  True False]
[1 2]


В numpy можно работать не только с векторами, но и с матрицами и массивами большей размерности. Давайте создадим матрицу, которая состоит из одних единиц.

In [0]:
matrix = np.ones((2, 4))

In [0]:
matrix.shape

(2, 4)

In [0]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Над матрицами мы можем выполнять все те же операции, что и над векторами. Также мы можем считать среднее, сумму как по всем элементам, так и вдоль осей.

In [0]:
np.sum(matrix)

8.0

In [0]:
np.sum(matrix, axis=1)

array([4., 4.])

Можем создавать случайный матрицы.

In [0]:
random_matrix = np.random.normal(size=(2, 2))
random_matrix

array([[-0.15202536,  0.04675802],
       [ 0.60686314, -0.45267678]])

Можем умножать матрицы и выполнять различные операции линейной алгебры.

In [0]:
matrix.T @ random_matrix

array([[ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875]])

In [0]:
np.linalg.det(random_matrix)

0.040442629348055266

In [0]:
np.linalg.matrix_rank(random_matrix)

2